import puppeteer from 'puppeteer';
const browser = await puppeteer.launch({ args: ['--no-sandbox'] });
const page = await browser.newPage();
await page.setViewport({ width: 1440, height: 900 });
await page.goto('https://luciennespa.beauty/home', { waitUntil: 'networkidle0', timeout: 30000 });
await page.screenshot({ path: '/tmp/prod_home.png' });
await page.setViewport({ width: 390, height: 844 });
await page.goto('https://luciennespa.beauty/home', { waitUntil: 'networkidle0', timeout: 30000 });
await page.screenshot({ path: '/tmp/prod_home_mobile.png' });
await browser.close();
console.log('DONE');
