import { createGiftCard, createMembershipPlan, createMembershipSubscription } from '../actions'
import { Badge, Card, EmptyState, formatMXN, PageHeader } from '../_components/AdminUI'
import { getClients, getMemberships } from '../../lib/admin-data'

export const dynamic = 'force-dynamic'

export default async function MembershipsPage() {
  const [data, clients] = await Promise.all([getMemberships(), getClients()])
  return <div className="admin-page">
    <PageHeader eyebrow="Retención y regalo" title="Membresías y gift cards" description="Planes, renovaciones, sesiones disponibles y certificados reales." />
    <div className="admin-grid admin-grid--2">
      <Card title="Suscripciones" subtitle={`${data.subscriptions.length} registros`}>
        {data.subscriptions.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Clienta</th><th>Plan</th><th>Estado</th><th>Renovación</th><th>Sesiones</th></tr></thead><tbody>{data.subscriptions.map((item) => <tr key={Number(item.id)}><td><strong>{String(item.clienta)}</strong></td><td>{String(item.plan)}</td><td><Badge status={String(item.estado)}/></td><td>{item.renovacion ? String(item.renovacion).slice(0,10) : '—'}</td><td className="admin-number">{Number(item.sesiones_disponibles || 0)}</td></tr>)}</tbody></table></div> : <EmptyState title="Sin suscripciones" description="Crea los planes de Lucienne y asigna el primero a una clienta." />}
        <div className="admin-divider"/><details><summary className="admin-secondary-button" style={{ width: 'fit-content' }}>Asignar membresía</summary><form action={createMembershipSubscription} className="admin-form" style={{ marginTop: 16 }}><label>Clienta<select name="clienteId" required defaultValue=""><option value="" disabled>Selecciona</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.nombre}</option>)}</select></label><label>Plan<select name="planId" required defaultValue=""><option value="" disabled>Selecciona</option>{data.plans.filter((plan) => Boolean(plan.activo)).map((plan) => <option value={Number(plan.id)} key={Number(plan.id)}>{String(plan.nombre)}</option>)}</select></label><label>Próxima renovación<input name="renovacion" type="date"/></label><button className="admin-primary-button">Activar membresía</button></form></details>
      </Card>
      <Card title="Planes" subtitle={`${data.plans.length} configurados`}>
        {data.plans.length ? <div className="admin-list">{data.plans.map((plan) => <div className="admin-list-row" key={Number(plan.id)}><div className="admin-list-row__main"><strong>{String(plan.nombre)}</strong><span>{Number(plan.sesiones_mes)} sesiones · {Array.isArray(plan.beneficios) ? plan.beneficios.join(', ') : ''}</span></div><span className="admin-money">{formatMXN(Number(plan.precio_mensual))}</span></div>)}</div> : <EmptyState title="Sin planes inventados" description="El panel anterior mostraba tres planes ficticios. Aquí sólo aparecerán los que dirección configure." />}
        <div className="admin-divider"/><details><summary className="admin-secondary-button" style={{ width: 'fit-content' }}>Crear plan</summary><form action={createMembershipPlan} className="admin-form" style={{ marginTop: 16 }}><label>Nombre<input name="nombre" required/></label><label>Mensualidad<input name="precio" type="number" min="0" step="0.01" required/></label><label>Sesiones por mes<input name="sesiones" type="number" min="0" defaultValue="0"/></label><label>Beneficios<input name="beneficios" placeholder="Separa cada beneficio con coma"/></label><button className="admin-primary-button">Guardar plan</button></form></details>
      </Card>
    </div>
    <Card title="Gift cards" subtitle={`${data.giftCards.length} certificados emitidos`} className="admin-memberships-gifts">
      {data.giftCards.length ? <div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Código</th><th>Destinatario</th><th>Correo</th><th>Monto</th><th>Estado</th></tr></thead><tbody>{data.giftCards.map((gift) => <tr key={Number(gift.id)}><td><strong>{String(gift.codigo)}</strong></td><td>{String(gift.destinatario_nombre || '—')}</td><td>{String(gift.destinatario_email || '—')}</td><td className="admin-money">{formatMXN(Number(gift.monto))}</td><td><Badge status={String(gift.estado)}/></td></tr>)}</tbody></table></div> : <EmptyState title="Aún no hay gift cards" description="Los certificados comprados en la app o creados por recepción aparecerán aquí." />}
      <div className="admin-divider"/><details><summary className="admin-secondary-button" style={{ width: 'fit-content' }}>Emitir gift card</summary><form action={createGiftCard} className="admin-form admin-form--2" style={{ marginTop: 16 }}><label>Monto<input name="monto" type="number" min="1" step="1" required/></label><label>Compradora<select name="clienteId" defaultValue=""><option value="">Sin vincular</option>{clients.map((client) => <option value={client.id} key={client.id}>{client.nombre}</option>)}</select></label><label>Destinatario<input name="destinatario"/></label><label>Correo destino<input name="email" type="email"/></label><label style={{ gridColumn: '1 / -1' }}>Mensaje<textarea name="mensaje"/></label><button className="admin-primary-button">Emitir certificado</button></form></details>
    </Card>
  </div>
}
